'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Entry_Penduduk

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''tbnik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnik As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbnama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbnama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbtemplhr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbtemplhr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbtgllhr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbtgllhr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbLaki control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLaki As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbPerempuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbPerempuan As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''tbAlamat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAlamat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddPekerjaan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPekerjaan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddNegara control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddNegara As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddPendididkan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddPendididkan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddAgama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddAgama As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tbPaspor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPaspor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbKitap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbKitap As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbAyah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAyah As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbIbu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbIbu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tbket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbket As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSimpan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimpan As Global.System.Web.UI.WebControls.Button
End Class
